language: rust
rust:
  - stable 
  - nightly
os:
  - osx
  - linux
env:
  - FEATURES="" IOS_ARCHS=""
matrix:
  include:
    - os: osx
      rust: stable
      env: FEATURES="exception verify_message" IOS_ARCHS=""
    - os: osx
      osx_image: xcode7.2
      rust: nightly
      env: FEATURES="exception" IOS_ARCHS="i386 x86_64 armv7 armv7s aarch64"
sudo: false
install: ./travis_install.sh
script: ./travis_test.sh
addons:
  apt:
    packages:
      - gnustep-devel
